[project]
name = "govec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pradyoth", email = "sppradyoth@outlook.com" }
]
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "pyright>=1.1.407",
    "ruff>=0.12.9",
]
test = []

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
build-backend = "uv_build"


[tool.uv]
package = true