# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from govec.proto import govec_pb2 as govec_dot_proto_dot_govec__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in govec/proto/govec_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GoVecServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/govec.v1.GoVecService/Insert',
                request_serializer=govec_dot_proto_dot_govec__pb2.InsertRequest.SerializeToString,
                response_deserializer=govec_dot_proto_dot_govec__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.BatchInsert = channel.stream_unary(
                '/govec.v1.GoVecService/BatchInsert',
                request_serializer=govec_dot_proto_dot_govec__pb2.InsertRequest.SerializeToString,
                response_deserializer=govec_dot_proto_dot_govec__pb2.BatchInsertResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/govec.v1.GoVecService/Search',
                request_serializer=govec_dot_proto_dot_govec__pb2.SearchRequest.SerializeToString,
                response_deserializer=govec_dot_proto_dot_govec__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/govec.v1.GoVecService/Delete',
                request_serializer=govec_dot_proto_dot_govec__pb2.DeleteRequest.SerializeToString,
                response_deserializer=govec_dot_proto_dot_govec__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/govec.v1.GoVecService/Stats',
                request_serializer=govec_dot_proto_dot_govec__pb2.StatsRequest.SerializeToString,
                response_deserializer=govec_dot_proto_dot_govec__pb2.StatsResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/govec.v1.GoVecService/Info',
                request_serializer=govec_dot_proto_dot_govec__pb2.InfoRequest.SerializeToString,
                response_deserializer=govec_dot_proto_dot_govec__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.Flush = channel.unary_unary(
                '/govec.v1.GoVecService/Flush',
                request_serializer=govec_dot_proto_dot_govec__pb2.FlushRequest.SerializeToString,
                response_deserializer=govec_dot_proto_dot_govec__pb2.FlushResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/govec.v1.GoVecService/Health',
                request_serializer=govec_dot_proto_dot_govec__pb2.HealthRequest.SerializeToString,
                response_deserializer=govec_dot_proto_dot_govec__pb2.HealthResponse.FromString,
                _registered_method=True)


class GoVecServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsert(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Flush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GoVecServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=govec_dot_proto_dot_govec__pb2.InsertRequest.FromString,
                    response_serializer=govec_dot_proto_dot_govec__pb2.InsertResponse.SerializeToString,
            ),
            'BatchInsert': grpc.stream_unary_rpc_method_handler(
                    servicer.BatchInsert,
                    request_deserializer=govec_dot_proto_dot_govec__pb2.InsertRequest.FromString,
                    response_serializer=govec_dot_proto_dot_govec__pb2.BatchInsertResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=govec_dot_proto_dot_govec__pb2.SearchRequest.FromString,
                    response_serializer=govec_dot_proto_dot_govec__pb2.SearchResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=govec_dot_proto_dot_govec__pb2.DeleteRequest.FromString,
                    response_serializer=govec_dot_proto_dot_govec__pb2.DeleteResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=govec_dot_proto_dot_govec__pb2.StatsRequest.FromString,
                    response_serializer=govec_dot_proto_dot_govec__pb2.StatsResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=govec_dot_proto_dot_govec__pb2.InfoRequest.FromString,
                    response_serializer=govec_dot_proto_dot_govec__pb2.InfoResponse.SerializeToString,
            ),
            'Flush': grpc.unary_unary_rpc_method_handler(
                    servicer.Flush,
                    request_deserializer=govec_dot_proto_dot_govec__pb2.FlushRequest.FromString,
                    response_serializer=govec_dot_proto_dot_govec__pb2.FlushResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=govec_dot_proto_dot_govec__pb2.HealthRequest.FromString,
                    response_serializer=govec_dot_proto_dot_govec__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'govec.v1.GoVecService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('govec.v1.GoVecService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GoVecService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/govec.v1.GoVecService/Insert',
            govec_dot_proto_dot_govec__pb2.InsertRequest.SerializeToString,
            govec_dot_proto_dot_govec__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsert(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/govec.v1.GoVecService/BatchInsert',
            govec_dot_proto_dot_govec__pb2.InsertRequest.SerializeToString,
            govec_dot_proto_dot_govec__pb2.BatchInsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/govec.v1.GoVecService/Search',
            govec_dot_proto_dot_govec__pb2.SearchRequest.SerializeToString,
            govec_dot_proto_dot_govec__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/govec.v1.GoVecService/Delete',
            govec_dot_proto_dot_govec__pb2.DeleteRequest.SerializeToString,
            govec_dot_proto_dot_govec__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/govec.v1.GoVecService/Stats',
            govec_dot_proto_dot_govec__pb2.StatsRequest.SerializeToString,
            govec_dot_proto_dot_govec__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/govec.v1.GoVecService/Info',
            govec_dot_proto_dot_govec__pb2.InfoRequest.SerializeToString,
            govec_dot_proto_dot_govec__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/govec.v1.GoVecService/Flush',
            govec_dot_proto_dot_govec__pb2.FlushRequest.SerializeToString,
            govec_dot_proto_dot_govec__pb2.FlushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/govec.v1.GoVecService/Health',
            govec_dot_proto_dot_govec__pb2.HealthRequest.SerializeToString,
            govec_dot_proto_dot_govec__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
